---
services:
  announcer:
    build: .
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - DISCORD_CHANNEL_ID=${DISCORD_CHANNEL_ID}
      - SCRAPER_BACKEND=${SCRAPER_BACKEND:-graphql}
      - TAGS=${TAGS:-unifi-protect,unifi-network}
    env_file: [.env]
    volumes:
      - ./cache:/cache

  dev:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - DISCORD_CHANNEL_ID=${DISCORD_CHANNEL_ID}
      - SCRAPER_BACKEND=${SCRAPER_BACKEND:-graphql}
      - TAGS=${TAGS:-unifi-protect,unifi-network}
    env_file: [.env]
    volumes:
      - .:/app
      - dev_venv:/app/.venv

volumes:
  dev_venv:
