[project]
name = "unifi-release-announcer"
version = "0.2.14"
description = "Discord bot that announces new UniFi releases"
authors = [
    {name = "damacus"}
]
requires-python = ">=3.13"
dependencies = [
    "discord.py",
    "aiohttp>=3.9.0",
]

[project.optional-dependencies]
dev = [
    "mkdocs",
    "mkdocs-material",
]
